# Generated by Django 2.1 on 2021-01-30 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Pos', models.IntegerField()),
                ('AB', models.IntegerField()),
                ('H', models.IntegerField()),
                ('R', models.IntegerField()),
                ('HR', models.IntegerField()),
                ('RBI', models.IntegerField()),
                ('SB', models.IntegerField()),
                ('Salary', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
