# Generated by Django 2.1 on 2021-01-31 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_batter_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batter',
            old_name='AB',
            new_name='ab',
        ),
        migrations.RenameField(
            model_name='batter',
            old_name='H',
            new_name='h',
        ),
        migrations.RenameField(
            model_name='batter',
            old_name='HR',
            new_name='hr',
        ),
        migrations.RenameField(
            model_name='batter',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='batter',
            old_name='Pos',
            new_name='pos',
        ),
        migrations.RenameField(
            model_name='batter',
            old_name='R',
            new_name='r',
        ),
        migrations.RenameField(
            model_name='batter',
            old_name='RBI',
            new_name='rbi',
        ),
        migrations.RenameField(
            model_name='batter',
            old_name='Salary',
            new_name='salary',
        ),
        migrations.RenameField(
            model_name='batter',
            old_name='SB',
            new_name='sb',
        ),
    ]
