# Generated by Django 2.1 on 2021-01-31 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_team_catcher1'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='catcher2',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catcher2', to='hello.Batter'),
        ),
        migrations.AddField(
            model_name='team',
            name='cornerINF',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cornerINF', to='hello.Batter'),
        ),
        migrations.AddField(
            model_name='team',
            name='first',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='first', to='hello.Batter'),
        ),
        migrations.AddField(
            model_name='team',
            name='middleINF',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='middleINF', to='hello.Batter'),
        ),
        migrations.AddField(
            model_name='team',
            name='of1',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='of1', to='hello.Batter'),
        ),
        migrations.AddField(
            model_name='team',
            name='of2',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='of2', to='hello.Batter'),
        ),
        migrations.AddField(
            model_name='team',
            name='of3',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='of3', to='hello.Batter'),
        ),
        migrations.AddField(
            model_name='team',
            name='of4',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='of4', to='hello.Batter'),
        ),
        migrations.AddField(
            model_name='team',
            name='of5',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='of5', to='hello.Batter'),
        ),
        migrations.AddField(
            model_name='team',
            name='second',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='second', to='hello.Batter'),
        ),
        migrations.AddField(
            model_name='team',
            name='shortstop',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shortstop', to='hello.Batter'),
        ),
        migrations.AddField(
            model_name='team',
            name='third',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='third', to='hello.Batter'),
        ),
        migrations.AddField(
            model_name='team',
            name='utility',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='utility', to='hello.Batter'),
        ),
        migrations.AlterField(
            model_name='team',
            name='catcher1',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catcher1', to='hello.Batter'),
        ),
    ]
