# Generated by Django 2.1 on 2021-01-31 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_auto_20210130_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='catcher1',
        ),
        migrations.RemoveField(
            model_name='team',
            name='catcher2',
        ),
        migrations.RemoveField(
            model_name='team',
            name='cornerINF',
        ),
        migrations.RemoveField(
            model_name='team',
            name='first',
        ),
        migrations.RemoveField(
            model_name='team',
            name='middleINF',
        ),
        migrations.RemoveField(
            model_name='team',
            name='of1',
        ),
        migrations.RemoveField(
            model_name='team',
            name='of2',
        ),
        migrations.RemoveField(
            model_name='team',
            name='of3',
        ),
        migrations.RemoveField(
            model_name='team',
            name='of4',
        ),
        migrations.RemoveField(
            model_name='team',
            name='of5',
        ),
        migrations.RemoveField(
            model_name='team',
            name='second',
        ),
        migrations.RemoveField(
            model_name='team',
            name='shortstop',
        ),
        migrations.RemoveField(
            model_name='team',
            name='third',
        ),
        migrations.RemoveField(
            model_name='team',
            name='utility',
        ),
        migrations.AddField(
            model_name='batter',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='hello.Team'),
        ),
        migrations.AddField(
            model_name='team',
            name='league',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
